version: '2.4'

services:
  app:
    image: nexus3_local:3.38.0
    build:
      context: .
    ports:
      - 8080:8081
    volumes:
      - "nexus-data:/nexus-data"
  
  alpine-test:
    image: alpine-test:local
    build: 
      context: .
      dockerfile: Dockerfile.alpine
    entrypoint: ["sleep", "100000000000000"]

volumes:
  nexus-data: {}
